spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=d829c1d01055aa0acd156d59ff8d59382898f7bd3c83d31cba9ae443cda37c61
spring.datasource.password=sk_MTMaG9gd-w1Fxfq_0iPwA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect